#!/bin/sh
# realpath-compat by Hugo Josefson is marked with CC0 1.0. To view a copy of this license, visit http://creativecommons.org/publicdomain/zero/1.0

set -e

if ! [ -e "$1" ]; then
  echo "$0: could not find \"$1\"" >&2
  exit 1
fi

realpath "$1" 2>/dev/null \
|| readlink -f "$1" 2>/dev/null \
|| zsh -c 'echo ${0:A}' "$1" 2>/dev/null \
|| python3 -c "import os; import sys; print(os.path.realpath(sys.argv[1]))" "$1" 2>/dev/null \
|| node -e "console.log(require('fs').realpathSync(process.argv[1]))" "$1" 2>/dev/null \
|| echo "$0: could not find real path for \"$1\"" >&2
